### ISSUE TITLE
Kong Error MISSING PRIMARY KEY FIELD

### ISSUE THREAD

**Issue by Afzaal786** [Getsidecar/ansible-role-kong#6]
![capture](https://cloud.githubusercontent.com/assets/22439816/23214524/cefb82e6-f930-11e6-9ddb-28b05160e54d.PNG)

**Comment by davewalk** [comment]
This repo is no longer maintained. Feel free to fork.

**Comment by Afzaal786** [comment]
@davewalk i got it
